title : Jon Couldridge
tagline: Beforan's Pages
author :
  name : Jon Couldridge
  email : jcouldridge@outlook.com
permalink: /:year/:month/:day/:title.html

markdown: redcarpet2
highlighter: pygments


