title: Beforan's Pages

markdown: redcarpet
redcarpet:
  extensions: [ "tables", "no_intra_emphasis", "autolink", "smart" ]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
