title: Beforan's Pages

markdown: redcarpet
redcarpet:
  extensions: [ "tables", "no_intra_emphasis", "autolink", "smart", "strikethrough", "space_after_headers", "superscript", "highlight", "footnotes", "abbreviations" ]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
